### ISSUE TITLE
Bug on sequential data

### ISSUE THREAD

**Issue by susie-ku** [sb-ai-lab/LightAutoML#124]
Wrong logic in conditions
Correct both for numeric and categoric features
cat: https://github.com/sb-ai-lab/LightAutoML/blob/0bcbb8523b499e27eea493eca1d44b247b42e4b0/lightautoml/ml_algo/dl_model.py#L316C22-L316C22
cont: https://github.com/sb-ai-lab/LightAutoML/blob/0bcbb8523b499e27eea493eca1d44b247b42e4b0/lightautoml/ml_algo/dl_model.py#L303

To reproduce: for Autoint and FTTransformer set use_cat to False, advanced_roles to False and all features to numeric

**Comment by susie-ku** [comment]
Add missing default embedders to seq embedders
https://github.com/sb-ai-lab/LightAutoML/blob/0bcbb8523b499e27eea493eca1d44b247b42e4b0/lightautoml/ml_algo/dl_model.py#L113

**Comment by D1MK4real** [comment]
Done.
