### ISSUE TITLE
Ошибка при отработке кода

### ISSUE THREAD

**Issue by jhx95** [sb-ai-lab/LightAutoML#132]
## ❓ Questions and Help

Добрый день! Вчера работало все исправно, сегодня сутра получил ошибку вот такого рода:
AttributeError: module 'lightautoml.reader' has no attribute 'fit_read'
Подскажите пожалуйста, как решить ее.

![image](https://github.com/sb-ai-lab/LightAutoML/assets/37826744/e42d4790-da32-428e-a742-96c9ee25583f)

**Comment by alexmryzhkov** [comment]
@jhx95 can't reproduce your issue (I have tried with 0.3.8.1 lightautoml) - could you please provide more details like a sample code?
