### ISSUE TITLE
automl.fit_predict() raises KeyError: 'index' when used with latest version of pandas==2.1.1

### ISSUE THREAD

**Issue by refaat31** [sb-ai-lab/LightAutoML#140]
## Explanation
I am getting a KeyError when executing the automl.fit_predict() function while following this notebook - https://colab.research.google.com/github/AILab-MLTools/LightAutoML/blob/master/examples/tutorials/Tutorial_1_basics.ipynb

## error trace

![lightautoml](https://github.com/sb-ai-lab/LightAutoML/assets/47078433/1ce775f5-be03-4a48-bf05-36bc24417908)

## version used:
Python 3.10.12
lightautoml==0.3.8b1
pandas==2.1.1

## References:
* Reference notebook showing the output of the error : https://colab.research.google.com/drive/1X-hLB7O4wF8gyU6gBd09KzYq83GTIF1E

* With pandas==1.4.3, however, I can get the same code to run without any errors raised. - https://colab.research.google.com/drive/1S-WRjWMCfM99kS5ZMvlVJoLpwcWQiTL2

**Comment by fingoldo** [comment]
Очень отзывчивые разработчики...

**Comment by alexmryzhkov** [comment]
Hi @fingoldo,

Currently we are working on migration to pandas 2.x but yes, this process takes longer than all of us expected because of the dramatic changes in pandas lib.

Alex

**Comment by Uptimolli** [comment]
Hi! We added support for pandas version >=2.0.0 in this commit ([commit link](https://github.com/sb-ai-lab/LightAutoML/commit/a8c4e90f7616a30bd46bd43e92feae62a90be9af)). You'll soon be able to download it from PyPi after 0.4.0 Release.
