### ISSUE TITLE
Unable to import TabularAutoML

### ISSUE THREAD

**Issue by jatinchawda1503** [sb-ai-lab/LightAutoML#143]
## 🐛 Bug

Hello,
I am trying to use LightAutoML in my local, Google Colab and Kaggle with the latest version.

when I am importing 

```
from lightautoml.automl.presets.tabular_presets import TabularAutoML
from lightautoml.tasks import Task
```

I get this error 

---------------------------------------------------------------------------
```
TypeError                                 Traceback (most recent call last)
[<ipython-input-8-e1576580262b>](https://localhost:8080/#) in <cell line: 17>()
     15 
     16 # LightAutoML presets, task and report generation
---> 17 from lightautoml.automl.presets.tabular_presets import TabularAutoML
     18 from lightautoml.tasks import Task

10 frames
[/usr/local/lib/python3.10/dist-packages/log_calls/log_calls.py](https://localhost:8080/#) in _add_class_attrs(self, klass)
   2136         this_deco_class = self.__class__
   2137         this_deco_class_name = this_deco_class.__name__
-> 2138         setattr(
   2139             klass,
   2140             'get_' + this_deco_class_name + '_wrapper',

TypeError: cannot set 'get_record_history_wrapper' attribute of immutable type 'object'
```

### To Reproduce

1. https://colab.research.google.com/github/AILab-MLTools/LightAutoML/blob/master/examples/tutorials/Tutorial_9_neural_networks.ipynb
1. Install the Library
3. Try to Import -> from lightautoml.automl.presets.tabular_presets import TabularAutoML

Attached is the screenshot of the error.

<img width="955" alt="image" src="https://github.com/sb-ai-lab/LightAutoML/assets/38835306/5e1fb019-9e30-4060-95df-d0f68529da36">

**Comment by alexmryzhkov** [comment]
@jatinchawda1503 `pip install lightautoml==0.3.8b1` will solve your issue as it is suitable for Colab's python 3.10
