### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by sandeshregmi** [sb-ai-lab/LightAutoML#144]
Hello, I kept getting this error when trying to install the package `!pip install -U lightautoml[all]` Not sure how to address this, any help would be greatly appreciated.

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-3-e1576580262b>](https://localhost:8080/#) in <cell line: 17>()
     15 
     16 # LightAutoML presets, task and report generation
---> 17 from lightautoml.automl.presets.tabular_presets import TabularAutoML
     18 from lightautoml.tasks import `Task`

10 frames
[/usr/local/lib/python3.10/dist-packages/log_calls/log_calls.py](https://localhost:8080/#) in _add_class_attrs(self, klass)
   2136         this_deco_class = self.__class__
   2137         this_deco_class_name = this_deco_class.__name__
-> 2138         setattr(
   2139             klass,
   2140             'get_' + this_deco_class_name + '_wrapper',

TypeError: cannot set 'get_record_history_wrapper' attribute of immutable type 'object'

**Comment by alexmryzhkov** [comment]
@sandeshregmi please try `pip install lightautoml==0.3.8b1`
