### ISSUE TITLE
Use Py-boost in LightAutoML

### ISSUE THREAD

**Issue by numomcmc** [sb-ai-lab/LightAutoML#150]
### Before asking:
1. search the issues.
2. search the docs.

#### What is your question?

Per your introduction video 5.1 [New LightAutoML functionality[([5.1 New LightAutoML functionality](https://youtu.be/aEgl5NJwOx8?si=qwHOFcpjmebLWcb1) from 7 months ago, LightAutoML is now supporting py-boost.  I'd like to give py-boost a try but I am unable to find any documentation on this feature.  So what is the status?  Is it support or not?  Where can I find more details?
 
#### What have you tried?
Search of "py-boost", "pyboost", "sketch" return zero results from both Github and [Read](https://lightautoml.readthedocs.io/en/latest).

**Comment by btbpanda** [comment]
Hello @numomcmc, thanks for your interest in py-boost library.  It is separated from LighAutoML, you can check it [here](https://github.com/sb-ai-lab/Py-Boost)

**Comment by numomcmc** [comment]
Hi Anton

Well, it was mentioned in the "New LightAutoML functionality" video!
😅   I guess the team decided not to incorporate it into LAMA.  Kind of a
shame, it would have been great to have CatBoost, LightGBM and Py-Boost all
supported in LAMA.  I guess Py-boost is not getting the traction...

Thank you for your reply!
S
