### ISSUE TITLE
The 'group' parameter cannot be applied in the roles of the fit_predict function in TabularAutoML.

### ISSUE THREAD

**Issue by yuuniee** [sb-ai-lab/LightAutoML#153]
## 🐛 Bug

 - The 'group' parameter cannot be applied in the roles of the fit_predict function in TabularAutoML.
 - As a result of backtracking the code, I found that the 'group' item was not included in the CV split process.

### To Reproduce

1. Run -> TabularAutoML().fit_predict(..., roles={'target': TARGET_NAME, 'group': GROUP_NAME})
2. "lightautoml > reader > utils.py > set_sklearn_folds()" <- Here, check if the 'group: Optional[np.ndarray]' variable has a value.

### Expected behavior

 - The CV split method changes depending on the 'group' designation above.

### Additional context

 - This was resolved by adding the following code to line 322 of "lightautoml > reader > base.py".
 - "kwargs["group"] = train_data.loc[:, roles["group"]]"

The issue was found in version "0.3.8.1" and is unknown for other versions.

I am always grateful for your open source contributions.
Thank you.

### Checklist
- [ ] bug description
- [ ] steps to reproduce
- [ ] expected behavior
- [ ] code sample / screenshots

**Comment by alexmryzhkov** [comment]
Hi @yuuniee, 

Thanks for the detailed description of the problem with the models validation. We will for sure take a look into it.

Alex

**Comment by screengreen** [comment]
Hi @yuuniee,

We checked correctness of CV split with the 'group' parameter. We tried several most popular task for it ['binary', 'multiclass', 'reg', 'multilevel'] and didn't find any issues with it. 


what you tried to add "_kwargs["group"] = train_data.loc[:, roles["group"]]_" is implemented here: https://github.com/sb-ai-lab/LightAutoML/blob/b4ace0c63ebf72b08b9c4fb82450f529c2c55958/lightautoml/reader/base.py#L311

if you want to examine it yourself, you can check the attached .ipynb file, that shows the 'group' parameter effect.
[Tutorial_1_basics_check_group_parameter.ipynb.zip](https://github.com/user-attachments/files/16349086/Tutorial_1_basics_check_group_parameter.ipynb.zip)

if it doesn't solve your problem, please provide additional information

Andrew
