### ISSUE TITLE
Model reuse is not possible when using the 'is_snap' option.

### ISSUE THREAD

**Issue by yuuniee** [sb-ai-lab/LightAutoML#154]
## 🐛 Bug

 - Model reuse is not possible when using the 'is_snap' option.

### To Reproduce
 - I tried were:
```python
algo = ['denselight', ]
automl_model = TabularAutoML(
    task = task, 
    timeout = TIMEOUT,
    cpu_limit = N_THREADS,
    gpu_ids='0',
    general_params = {"use_algos": [algo]}, # ['nn', 'mlp', 'dense', 'denselight', 'resnet', 'snn', 'node', 'autoint', 'fttransformer'] or custom torch model
    nn_params = {
        "n_epochs": EPOCHS, 
        "bs": TRAIN_BS, 
        "num_workers": 0, 
        "path_to_save": None, 
        "freeze_defaults": True, # False is Heavy...
        "cont_embedder": use_plr(USE_PLR), # 'linear' is better
        "cat_embedder": 'cat',
        "scheduler_params": { 'patience': 3, 'factor': 0.5, 'min_lr': 0.00001 },
        "opt_params": { 'lr': 1e-2,
                        'weight_decay': 0 },
        "drop_rate": 0.01,
        "is_snap": True,
        "snap_params": { 'k': 9, 'early_stopping': True, 'patience': 1, 'swa': True },
    },
    nn_pipeline_params = {
        "use_qnt": USE_QNT, 
        "use_te": False
    },
    reader_params = {
        'n_jobs': N_THREADS, 
        'cv': N_FOLDS, 
        'random_state': SEED, 
        'advanced_roles': ADVANCED_ROLES
    }, 
)
oof_pred = automl_model.fit_predict(df_train, roles = roles, verbose = 3, )
```
 - Here, with the use of the {..., "is_snap": True,} option, reuse of the model becomes impossible and the resulting error code is as follows.
>self.best_loss = weights.pop("best_loss")
>KeyError: 'best_loss'

 - You can check the log of the actual situation at the following link. (time line number: 92)
 - https://www.kaggle.com/code/yuuniekiri/fork-of-home-credit-lightautoml-inference/log?scriptVersionId=183902165
 - Model training was done in version 0.3.8.1, and model inference was done in 0.3.8.

### Expected behavior

 - No problem with inference even when reusing.

### Additional context

 - This is an error in the process of re-calling 'best_loss', which was removed with pop.
 - I tried on 0.3.8.1 to retest and didn't find the issue. Maybe it only happens in 0.3.8.

Thank you.

### Checklist
- [ ] bug description
- [ ] #157
- [ ] expected behavior
- [ ] code sample / screenshots

**Comment by screengreen** [comment]
hi @yuuniee, 

Thanks for the detailed description of the problem. We fixed the issue in the 0.3.8.1 version. In particular we added this line 
https://github.com/sb-ai-lab/LightAutoML/blob/56cb7c5c5f4a4b61bc77b84473dcd4ebdbc37d7b/lightautoml/text/trainer.py#L236

Andrew
