### ISSUE TITLE
Custom model pipeline mentioned in the nn tutorial is not working for version 3.8

### ISSUE THREAD

**Issue by priyanshu7401** [sb-ai-lab/LightAutoML#167]
### To Reproduce

Hey there i have been trying to produce the simplenetplus model mentioned here:
https://lightautoml.readthedocs.io/en/latest/pages/tutorials/Tutorial_9_neural_networks.html
however it seems not to be working with version 3.8

**Comment by priyanshu7401** [comment]
getting error as 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
[<ipython-input-13-8476f675cacd>](https://localhost:8080/#) in <cell line: 10>()
      8     },
      9 )
---> 10 automl.fit_predict(tr_data, roles=roles, verbose=1)

3 frames
[/usr/local/lib/python3.10/dist-packages/lightautoml/pipelines/ml/base.py](https://localhost:8080/#) in fit_predict(self, train_valid)
    134 
    135         assert (
--> 136             len(predictions) > 0
    137         ), "Pipeline finished with 0 models for some reason.\nProbably one or more models failed"
    138 

AssertionError: Pipeline finished with 0 models for some reason.
Probably one or more models failed

**Comment by dev-rinchin** [comment]
Hi @priyanshu7401, 

1. Could you please provide a full stack trace by passing debug=True into TabularAutoML initialization?
```
automl = TabularAutoML(.., debug=True, ...)
automl.fit_predict(...)
```

2. Which version of lightautoml do you use?

**Comment by Uptimolli** [comment]
Hi! If you can change files for your task locally, please modify two lines at .../lightautoml/ml_algo/dl_model.py:

Change ```if input_type_by_name.get(params["model"], "flat") == "seq" and is_cont``` to ```if input_type_by_name[params["model"]] == "seq" and is_cont```

and

Change ```if input_type_by_name.get(params["model"], "flat") == "seq" and is_cat``` to ```if input_type_by_name[params["model"]] == "seq" and is_cat```

We will fix it in the next release. Thank you for bringing this issue to our attention.

**Comment by Uptimolli** [comment]
Hi! The fix for this bug is available in master, you can install it from github:
pip install git+https://github.com/sb-ai-lab/LightAutoML.git
