### ISSUE TITLE
Get TypeError: cannot set 'get_record_history_wrapper' attribute of immutable type 'object' when import lightautoml

### ISSUE THREAD

**Issue by adelkhalilov** [sb-ai-lab/LightAutoML#169]
## I try to import anything from library lightautoml, but get error `Get TypeError: cannot set 'get_record_history_wrapper' attribute of immutable type 'object'`. 
I have python3.12 version and I made new clean env for using LightAutoML, onlu installed LightAutoML package and got this trouble. Can you help me please?

#### Error on the screen
<img width="805" alt="image" src="https://github.com/user-attachments/assets/9c01640e-d276-416b-9320-57f565bd61c2">

**Comment by Uptimolli** [comment]
Question is solved by direct install from git (https://github.com/sb-ai-lab/LightAutoML).

Current version from pypi isn't support 3.12 version
