### ISSUE TITLE
Make torch as necessary part only for cv or nlp tasks

### ISSUE THREAD

**Issue by AzurTheOwl** [sb-ai-lab/LightAutoML#3]
**What's now:** Any LAMA installation also installing torch as dependency, and this takes more than 800MB additional space. 

**Trouble example:** I use LAMA for my project with tabular data and whenever project image is created - it takes up twice more space (1.6 GB) for features I don't ever need in this project.

**Idea:** Make additional extras for installation ([no-torch] or something like that) or remove torch from [report] installation.

**Comment by alexmryzhkov** [comment]
Hi @AzurTheOwl,

Torch is the main dependency for LightAutoML because of linear model based on Torch.

To decrease the size of installation you can manually install CPU version of Torch library beforehand (but in this case you will be unable to solve NLP and CV tasks using neural networks).

Alex
