### ISSUE TITLE
Use of deprecated pandas methods

### ISSUE THREAD

**Issue by eli-osherovich** [sb-ai-lab/LightAutoML#56]
### To Reproduce

Run some examples with categorical data. 

### Expected behavior
No warnings

### Additional context
`OrdinalEncoder` uses `pandas.Series.append()` which is deprecated. Meanwhile it results is a bunch of warnings, in the future it will fail.

### Checklist
- [x] bug description
- [x] steps to reproduce
- [x] expected behavior
- [x] code sample / screenshots

**Comment by BEPb** [comment]
pyhton 3.10
from lightautoml.automl.presets.tabular_presets import TabularAutoML
-->
from lightautoml.automl.presets.tabular_presets import TabularAutoML
