### ISSUE TITLE
TypeError: numpy boolean subtract, the - operator, is not supported

### ISSUE THREAD

**Issue by shravankoninti** [sb-ai-lab/LightAutoML#65]
Hi Team ,

I am running a regression problem. I  am getting this error.  Can you please help resolve.

TypeError: numpy boolean subtract, the `-` operator, is not supported, use the bitwise_xor, the `^` operator, or the logical_xor function instead.

![image](https://user-images.githubusercontent.com/6191291/214815556-ccb850b7-1d6c-4fd8-8411-617befb357be.png)

![image](https://user-images.githubusercontent.com/6191291/214815751-36c19b4b-4067-46e8-9ce1-5002cad81ce5.png)

**Comment by VaBun** [comment]
Hi, 
thank you for reporting!
Could you please provide us with the data description and the task you are running to reproduce the behavior?
It's best if you attach an URL to the data if it's possible.

**Comment by shravankoninti** [comment]
Unfortunately - this is part of some competition that is happening currently - Even if I provide that data it will not help because I have lot of derived features. Is there any way privately I can share the prepared data with you -  I meant the data I prepared for train and test information along with derived features! Please let me know!

**Comment by VaBun** [comment]
OK. First of all, try restarting the whole kernel and running your code again. If it didn't help, try to determine the `feature_name` causing the problem. If it's your self-prepared feature, you can show the piece of feature generation code.

**Comment by shravankoninti** [comment]
X.replace({False: 0, True: 1}, inplace=True)
test_X.replace({False: 0, True: 1}, inplace=True)   

BTW - This will solve the above error. Boolean values are expected to be replaced as int.
