### ISSUE TITLE
TypeError: cannot set 'get_record_history_wrapper' attribute of immutable type 'object'

### ISSUE THREAD

**Issue by Hoigr** [sb-ai-lab/LightAutoML#87]
In google colab when trying to execute the following code:
!pip install lightautoml

from lightautoml.automl.presets.tabular_presets import TabularAutoML
from lightautoml.tasks import Task

The following error is displayed:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-24-eeea93007d7a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from lightautoml.automl.presets.tabular_presets import TabularAutoML
      2 from lightautoml.tasks import Task

10 frames
[/usr/local/lib/python3.10/dist-packages/lightautoml/__init__.py](https://localhost:8080/#) in <module>
     14     __version__ = importlib_metadata.version(__name__)
     15 
---> 16     from .addons import *
     17     from .addons.utilization import *
     18     from .automl import *

[/usr/local/lib/python3.10/dist-packages/lightautoml/addons/utilization/__init__.py](https://localhost:8080/#) in <module>
      1 """Tools to configure resources utilization."""
----> 2 from .utilization import TimeUtilization
      3 
      4 __all__ = ['TimeUtilization']

[/usr/local/lib/python3.10/dist-packages/lightautoml/addons/utilization/utilization.py](https://localhost:8080/#) in <module>
      6 from log_calls import record_history
      7 
----> 8 from ...automl.base import AutoML
      9 from ...automl.blend import Blender, BestModelSelector
     10 from ...automl.presets.base import AutoMLPreset

[/usr/local/lib/python3.10/dist-packages/lightautoml/automl/base.py](https://localhost:8080/#) in <module>
      6 from log_calls import record_history
      7 
----> 8 from .blend import Blender, BestModelSelector
      9 from ..dataset.base import LAMLDataset
     10 from ..dataset.utils import concatenate

[/usr/local/lib/python3.10/dist-packages/lightautoml/automl/blend.py](https://localhost:8080/#) in <module>
      7 from scipy.optimize import minimize_scalar
      8 
----> 9 from ..dataset.base import LAMLDataset
     10 from ..dataset.np_pd_dataset import NumpyDataset
     11 from ..dataset.roles import NumericRole

[/usr/local/lib/python3.10/dist-packages/lightautoml/dataset/base.py](https://localhost:8080/#) in <module>
      6 from log_calls import record_history
      7 
----> 8 from .roles import ColumnRole
      9 from ..tasks.base import Task
     10 

[/usr/local/lib/python3.10/dist-packages/lightautoml/dataset/roles.py](https://localhost:8080/#) in <module>
     13 
     14 @record_history(enabled=False)
---> 15 class ColumnRole:
     16     """Abstract class for column role.
     17 

[/usr/local/lib/python3.10/dist-packages/log_calls/log_calls.py](https://localhost:8080/#) in __call__(self, f_or_klass)
   1689             #+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*+*
   1690 
-> 1691             self._class__call__(klass)      # modifies klass (methods & inner classes) (if not builtin)
   1692             self._add_class_attrs(klass)    # v0.3.0v20 traps TypeError for builtins
   1693             return klass

[/usr/local/lib/python3.10/dist-packages/log_calls/log_calls.py](https://localhost:8080/#) in _class__call__(self, klass)
   1480                     new_omit += deco_obj._omit
   1481 
-> 1482                 new_class = self.__class__(
   1483                     settings=new_settings,
   1484                     only=new_only,

[/usr/local/lib/python3.10/dist-packages/log_calls/log_calls.py](https://localhost:8080/#) in __call__(self, f_or_klass)
   1690 
   1691             self._class__call__(klass)      # modifies klass (methods & inner classes) (if not builtin)
-> 1692             self._add_class_attrs(klass)    # v0.3.0v20 traps TypeError for builtins
   1693             return klass
   1694 

[/usr/local/lib/python3.10/dist-packages/log_calls/log_calls.py](https://localhost:8080/#) in _add_class_attrs(self, klass)
   2136         this_deco_class = self.__class__
   2137         this_deco_class_name = this_deco_class.__name__
-> 2138         setattr(
   2139             klass,
   2140             'get_' + this_deco_class_name + '_wrapper',

TypeError: cannot set 'get_record_history_wrapper' attribute of immutable type 'object'

**Comment by alexmryzhkov** [comment]
Hi @Hoigr,

This is the known problem because currently LightAutoML doesn’t support python 3.10. You can use it from our github repo if you need 3.10, but I recommend to replace python with 3.9 version.

Alex
