### ISSUE TITLE
Support python 3.10

### ISSUE THREAD

**Issue by neosh11** [sb-ai-lab/LightAutoML#90]
## 🚀 Feature Request

This package has become unusable on Kaggle and Colab

<img width="767" alt="Screen Shot 2023-06-16 at 6 54 22 pm" src="https://github.com/sb-ai-lab/LightAutoML/assets/12596969/654de200-8d9b-4a4c-8309-93e3496c5456">

### Motivation
Related to this: https://github.com/sb-ai-lab/LightAutoML/issues/89

### Proposal
Just update the config to support 3.10.10 and drop an update.

### Alternatives
- Downgrading every instance may be an option but no new users will know how to do this.

### Checklist
- [ X] feature proposal description
- [ X] motivation
- [ X] additional context / proposal alternatives review

**Comment by dev-rinchin** [comment]
Hi @neosh11, beta version for the next release 0.3.8b1 is available in pypi, it supports python 3.10. The stable version will be released in a few weeks.

Thank you!
